// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdj.project.eventcalendar.protobuf.Empty)
    com.google.protobuf.MessageOrBuilder {
}
