// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdj.project.eventcalendar.protobuf.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 event_id = 1;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string bodytext = 3;</code>
   * @return The bodytext.
   */
  java.lang.String getBodytext();
  /**
   * <code>string bodytext = 3;</code>
   * @return The bytes for bodytext.
   */
  com.google.protobuf.ByteString
      getBodytextBytes();

  /**
   * <code>string startTime = 4;</code>
   * @return The startTime.
   */
  java.lang.String getStartTime();
  /**
   * <code>string startTime = 4;</code>
   * @return The bytes for startTime.
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string endTime = 5;</code>
   * @return The endTime.
   */
  java.lang.String getEndTime();
  /**
   * <code>string endTime = 5;</code>
   * @return The bytes for endTime.
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();

  /**
   * <code>string address = 6;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 6;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   * @return The creator.
   */
  sdj.project.eventcalendar.protobuf.User getCreator();
  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   */
  sdj.project.eventcalendar.protobuf.UserOrBuilder getCreatorOrBuilder();
}
