// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package sdj.project.eventcalendar.protobuf;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdj_project_eventcalendar_protobuf_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdj_project_eventcalendar_protobuf_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\"sdj.project.eventcalendar." +
      "protobuf\"o\n\004User\022\017\n\007user_id\030\001 \001(\003\022\014\n\004nam" +
      "e\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\016\n\006gender\030\004 \001(" +
      "\t\022\025\n\rdate_of_birth\030\005 \001(\t\022\017\n\007address\030\006 \001(" +
      "\t2\225\004\n\017GRPCUserService\022e\n\017RPCfindUserById" +
      "\022(.sdj.project.eventcalendar.protobuf.Us" +
      "er\032(.sdj.project.eventcalendar.protobuf." +
      "User\022a\n\013RPCsaveUser\022(.sdj.project.eventc" +
      "alendar.protobuf.User\032(.sdj.project.even" +
      "tcalendar.protobuf.User\022c\n\rRPCupdateUser" +
      "\022(.sdj.project.eventcalendar.protobuf.Us" +
      "er\032(.sdj.project.eventcalendar.protobuf." +
      "User\022c\n\rRPCdeleteUser\022(.sdj.project.even" +
      "tcalendar.protobuf.User\032(.sdj.project.ev" +
      "entcalendar.protobuf.User\022n\n\024RPCGetListO" +
      "fAllUsers\022(.sdj.project.eventcalendar.pr" +
      "otobuf.User\032(.sdj.project.eventcalendar." +
      "protobuf.User\"\0000\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sdj_project_eventcalendar_protobuf_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdj_project_eventcalendar_protobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdj_project_eventcalendar_protobuf_User_descriptor,
        new java.lang.String[] { "UserId", "Name", "Password", "Gender", "DateOfBirth", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
