// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 event_id = 1;</code>
   * @return The eventId.
   */
  int getEventId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string bodytext = 3;</code>
   * @return The bodytext.
   */
  java.lang.String getBodytext();
  /**
   * <code>string bodytext = 3;</code>
   * @return The bytes for bodytext.
   */
  com.google.protobuf.ByteString
      getBodytextBytes();

  /**
   * <code>string startTime = 4;</code>
   * @return The startTime.
   */
  java.lang.String getStartTime();
  /**
   * <code>string startTime = 4;</code>
   * @return The bytes for startTime.
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string endTime = 5;</code>
   * @return The endTime.
   */
  java.lang.String getEndTime();
  /**
   * <code>string endTime = 5;</code>
   * @return The bytes for endTime.
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();

  /**
   * <code>string adrdess = 6;</code>
   * @return The adrdess.
   */
  java.lang.String getAdrdess();
  /**
   * <code>string adrdess = 6;</code>
   * @return The bytes for adrdess.
   */
  com.google.protobuf.ByteString
      getAdrdessBytes();
}
