// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string gender = 4;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 4;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string date_of_birth = 5;</code>
   * @return The dateOfBirth.
   */
  java.lang.String getDateOfBirth();
  /**
   * <code>string date_of_birth = 5;</code>
   * @return The bytes for dateOfBirth.
   */
  com.google.protobuf.ByteString
      getDateOfBirthBytes();

  /**
   * <code>string adrdess = 6;</code>
   * @return The adrdess.
   */
  java.lang.String getAdrdess();
  /**
   * <code>string adrdess = 6;</code>
   * @return The bytes for adrdess.
   */
  com.google.protobuf.ByteString
      getAdrdessBytes();
}
