// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\032\nUser.proto\"n\n\005Event\022\020\n\010ev" +
      "ent_id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010bodytext\030\003" +
      " \001(\t\022\021\n\tstartTime\030\004 \001(\t\022\017\n\007endTime\030\005 \001(\t" +
      "\022\017\n\007adrdess\030\006 \001(\t2\326\001\n\020GRPCEventService\022:" +
      "\n%RPCserverSideStreamingGetListOfEvents\022" +
      "\005.User\032\006.Event\"\0000\001\022\"\n\020RPCfindEventById\022\006" +
      ".Event\032\006.Event\022\036\n\014RPCsaveEvent\022\006.Event\032\006" +
      ".Event\022 \n\016RPCupdateEvent\022\006.Event\032\006.Event" +
      "\022 \n\016RPCdeleteEvent\022\006.Event\032\006.EventB\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          UserOuterClass.getDescriptor(),
        });
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "EventId", "Name", "Bodytext", "StartTime", "EndTime", "Adrdess", });
    UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
