// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

/**
 * Protobuf type {@code sdj.project.eventcalendar.protobuf.Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sdj.project.eventcalendar.protobuf.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    name_ = "";
    bodytext_ = "";
    startTime_ = "";
    endTime_ = "";
    address_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            eventId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            bodytext_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            startTime_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            endTime_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 58: {
            sdj.project.eventcalendar.protobuf.User.Builder subBuilder = null;
            if (creator_ != null) {
              subBuilder = creator_.toBuilder();
            }
            creator_ = input.readMessage(sdj.project.eventcalendar.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(creator_);
              creator_ = subBuilder.buildPartial();
            }

            break;
          }
          case 64: {

            isCompleted_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdj.project.eventcalendar.protobuf.EventOuterClass.internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdj.project.eventcalendar.protobuf.EventOuterClass.internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdj.project.eventcalendar.protobuf.Event.class, sdj.project.eventcalendar.protobuf.Event.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  private long eventId_;
  /**
   * <code>int64 event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public long getEventId() {
    return eventId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODYTEXT_FIELD_NUMBER = 3;
  private volatile java.lang.Object bodytext_;
  /**
   * <code>string bodytext = 3;</code>
   * @return The bodytext.
   */
  @java.lang.Override
  public java.lang.String getBodytext() {
    java.lang.Object ref = bodytext_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bodytext_ = s;
      return s;
    }
  }
  /**
   * <code>string bodytext = 3;</code>
   * @return The bytes for bodytext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodytextBytes() {
    java.lang.Object ref = bodytext_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bodytext_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTTIME_FIELD_NUMBER = 4;
  private volatile java.lang.Object startTime_;
  /**
   * <code>string startTime = 4;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public java.lang.String getStartTime() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTime_ = s;
      return s;
    }
  }
  /**
   * <code>string startTime = 4;</code>
   * @return The bytes for startTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartTimeBytes() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object endTime_;
  /**
   * <code>string endTime = 5;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public java.lang.String getEndTime() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTime_ = s;
      return s;
    }
  }
  /**
   * <code>string endTime = 5;</code>
   * @return The bytes for endTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndTimeBytes() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 6;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 6;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 6;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATOR_FIELD_NUMBER = 7;
  private sdj.project.eventcalendar.protobuf.User creator_;
  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   * @return Whether the creator field is set.
   */
  @java.lang.Override
  public boolean hasCreator() {
    return creator_ != null;
  }
  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   * @return The creator.
   */
  @java.lang.Override
  public sdj.project.eventcalendar.protobuf.User getCreator() {
    return creator_ == null ? sdj.project.eventcalendar.protobuf.User.getDefaultInstance() : creator_;
  }
  /**
   * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
   */
  @java.lang.Override
  public sdj.project.eventcalendar.protobuf.UserOrBuilder getCreatorOrBuilder() {
    return getCreator();
  }

  public static final int ISCOMPLETED_FIELD_NUMBER = 8;
  private boolean isCompleted_;
  /**
   * <code>bool isCompleted = 8;</code>
   * @return The isCompleted.
   */
  @java.lang.Override
  public boolean getIsCompleted() {
    return isCompleted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventId_ != 0L) {
      output.writeInt64(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bodytext_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bodytext_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, endTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, address_);
    }
    if (creator_ != null) {
      output.writeMessage(7, getCreator());
    }
    if (isCompleted_ != false) {
      output.writeBool(8, isCompleted_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bodytext_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bodytext_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, endTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, address_);
    }
    if (creator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getCreator());
    }
    if (isCompleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isCompleted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdj.project.eventcalendar.protobuf.Event)) {
      return super.equals(obj);
    }
    sdj.project.eventcalendar.protobuf.Event other = (sdj.project.eventcalendar.protobuf.Event) obj;

    if (getEventId()
        != other.getEventId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getBodytext()
        .equals(other.getBodytext())) return false;
    if (!getStartTime()
        .equals(other.getStartTime())) return false;
    if (!getEndTime()
        .equals(other.getEndTime())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (hasCreator() != other.hasCreator()) return false;
    if (hasCreator()) {
      if (!getCreator()
          .equals(other.getCreator())) return false;
    }
    if (getIsCompleted()
        != other.getIsCompleted()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BODYTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getBodytext().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getStartTime().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getEndTime().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    if (hasCreator()) {
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
    }
    hash = (37 * hash) + ISCOMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCompleted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sdj.project.eventcalendar.protobuf.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdj.project.eventcalendar.protobuf.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sdj.project.eventcalendar.protobuf.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdj.project.eventcalendar.protobuf.Event)
      sdj.project.eventcalendar.protobuf.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdj.project.eventcalendar.protobuf.EventOuterClass.internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdj.project.eventcalendar.protobuf.EventOuterClass.internal_static_sdj_project_eventcalendar_protobuf_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdj.project.eventcalendar.protobuf.Event.class, sdj.project.eventcalendar.protobuf.Event.Builder.class);
    }

    // Construct using sdj.project.eventcalendar.protobuf.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      eventId_ = 0L;

      name_ = "";

      bodytext_ = "";

      startTime_ = "";

      endTime_ = "";

      address_ = "";

      if (creatorBuilder_ == null) {
        creator_ = null;
      } else {
        creator_ = null;
        creatorBuilder_ = null;
      }
      isCompleted_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdj.project.eventcalendar.protobuf.EventOuterClass.internal_static_sdj_project_eventcalendar_protobuf_Event_descriptor;
    }

    @java.lang.Override
    public sdj.project.eventcalendar.protobuf.Event getDefaultInstanceForType() {
      return sdj.project.eventcalendar.protobuf.Event.getDefaultInstance();
    }

    @java.lang.Override
    public sdj.project.eventcalendar.protobuf.Event build() {
      sdj.project.eventcalendar.protobuf.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdj.project.eventcalendar.protobuf.Event buildPartial() {
      sdj.project.eventcalendar.protobuf.Event result = new sdj.project.eventcalendar.protobuf.Event(this);
      result.eventId_ = eventId_;
      result.name_ = name_;
      result.bodytext_ = bodytext_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.address_ = address_;
      if (creatorBuilder_ == null) {
        result.creator_ = creator_;
      } else {
        result.creator_ = creatorBuilder_.build();
      }
      result.isCompleted_ = isCompleted_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdj.project.eventcalendar.protobuf.Event) {
        return mergeFrom((sdj.project.eventcalendar.protobuf.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdj.project.eventcalendar.protobuf.Event other) {
      if (other == sdj.project.eventcalendar.protobuf.Event.getDefaultInstance()) return this;
      if (other.getEventId() != 0L) {
        setEventId(other.getEventId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getBodytext().isEmpty()) {
        bodytext_ = other.bodytext_;
        onChanged();
      }
      if (!other.getStartTime().isEmpty()) {
        startTime_ = other.startTime_;
        onChanged();
      }
      if (!other.getEndTime().isEmpty()) {
        endTime_ = other.endTime_;
        onChanged();
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.hasCreator()) {
        mergeCreator(other.getCreator());
      }
      if (other.getIsCompleted() != false) {
        setIsCompleted(other.getIsCompleted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sdj.project.eventcalendar.protobuf.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sdj.project.eventcalendar.protobuf.Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long eventId_ ;
    /**
     * <code>int64 event_id = 1;</code>
     * @return The eventId.
     */
    @java.lang.Override
    public long getEventId() {
      return eventId_;
    }
    /**
     * <code>int64 event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(long value) {
      
      eventId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      
      eventId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bodytext_ = "";
    /**
     * <code>string bodytext = 3;</code>
     * @return The bodytext.
     */
    public java.lang.String getBodytext() {
      java.lang.Object ref = bodytext_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bodytext_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bodytext = 3;</code>
     * @return The bytes for bodytext.
     */
    public com.google.protobuf.ByteString
        getBodytextBytes() {
      java.lang.Object ref = bodytext_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bodytext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bodytext = 3;</code>
     * @param value The bodytext to set.
     * @return This builder for chaining.
     */
    public Builder setBodytext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bodytext_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bodytext = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBodytext() {
      
      bodytext_ = getDefaultInstance().getBodytext();
      onChanged();
      return this;
    }
    /**
     * <code>string bodytext = 3;</code>
     * @param value The bytes for bodytext to set.
     * @return This builder for chaining.
     */
    public Builder setBodytextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bodytext_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object startTime_ = "";
    /**
     * <code>string startTime = 4;</code>
     * @return The startTime.
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string startTime = 4;</code>
     * @return The bytes for startTime.
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string startTime = 4;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = getDefaultInstance().getStartTime();
      onChanged();
      return this;
    }
    /**
     * <code>string startTime = 4;</code>
     * @param value The bytes for startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endTime_ = "";
    /**
     * <code>string endTime = 5;</code>
     * @return The endTime.
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endTime = 5;</code>
     * @return The bytes for endTime.
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endTime = 5;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = getDefaultInstance().getEndTime();
      onChanged();
      return this;
    }
    /**
     * <code>string endTime = 5;</code>
     * @param value The bytes for endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 6;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 6;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 6;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 6;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private sdj.project.eventcalendar.protobuf.User creator_;
    private com.google.protobuf.SingleFieldBuilderV3<
        sdj.project.eventcalendar.protobuf.User, sdj.project.eventcalendar.protobuf.User.Builder, sdj.project.eventcalendar.protobuf.UserOrBuilder> creatorBuilder_;
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     * @return Whether the creator field is set.
     */
    public boolean hasCreator() {
      return creatorBuilder_ != null || creator_ != null;
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     * @return The creator.
     */
    public sdj.project.eventcalendar.protobuf.User getCreator() {
      if (creatorBuilder_ == null) {
        return creator_ == null ? sdj.project.eventcalendar.protobuf.User.getDefaultInstance() : creator_;
      } else {
        return creatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public Builder setCreator(sdj.project.eventcalendar.protobuf.User value) {
      if (creatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        creator_ = value;
        onChanged();
      } else {
        creatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public Builder setCreator(
        sdj.project.eventcalendar.protobuf.User.Builder builderForValue) {
      if (creatorBuilder_ == null) {
        creator_ = builderForValue.build();
        onChanged();
      } else {
        creatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public Builder mergeCreator(sdj.project.eventcalendar.protobuf.User value) {
      if (creatorBuilder_ == null) {
        if (creator_ != null) {
          creator_ =
            sdj.project.eventcalendar.protobuf.User.newBuilder(creator_).mergeFrom(value).buildPartial();
        } else {
          creator_ = value;
        }
        onChanged();
      } else {
        creatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public Builder clearCreator() {
      if (creatorBuilder_ == null) {
        creator_ = null;
        onChanged();
      } else {
        creator_ = null;
        creatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public sdj.project.eventcalendar.protobuf.User.Builder getCreatorBuilder() {
      
      onChanged();
      return getCreatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    public sdj.project.eventcalendar.protobuf.UserOrBuilder getCreatorOrBuilder() {
      if (creatorBuilder_ != null) {
        return creatorBuilder_.getMessageOrBuilder();
      } else {
        return creator_ == null ?
            sdj.project.eventcalendar.protobuf.User.getDefaultInstance() : creator_;
      }
    }
    /**
     * <code>.sdj.project.eventcalendar.protobuf.User creator = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        sdj.project.eventcalendar.protobuf.User, sdj.project.eventcalendar.protobuf.User.Builder, sdj.project.eventcalendar.protobuf.UserOrBuilder> 
        getCreatorFieldBuilder() {
      if (creatorBuilder_ == null) {
        creatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            sdj.project.eventcalendar.protobuf.User, sdj.project.eventcalendar.protobuf.User.Builder, sdj.project.eventcalendar.protobuf.UserOrBuilder>(
                getCreator(),
                getParentForChildren(),
                isClean());
        creator_ = null;
      }
      return creatorBuilder_;
    }

    private boolean isCompleted_ ;
    /**
     * <code>bool isCompleted = 8;</code>
     * @return The isCompleted.
     */
    @java.lang.Override
    public boolean getIsCompleted() {
      return isCompleted_;
    }
    /**
     * <code>bool isCompleted = 8;</code>
     * @param value The isCompleted to set.
     * @return This builder for chaining.
     */
    public Builder setIsCompleted(boolean value) {
      
      isCompleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isCompleted = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCompleted() {
      
      isCompleted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sdj.project.eventcalendar.protobuf.Event)
  }

  // @@protoc_insertion_point(class_scope:sdj.project.eventcalendar.protobuf.Event)
  private static final sdj.project.eventcalendar.protobuf.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdj.project.eventcalendar.protobuf.Event();
  }

  public static sdj.project.eventcalendar.protobuf.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdj.project.eventcalendar.protobuf.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

