// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package sdj.project.eventcalendar.protobuf;

public interface JoinedEventsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdj.project.eventcalendar.protobuf.JoinedEvents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 event_id = 2;</code>
   * @return The eventId.
   */
  long getEventId();
}
