// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package sdj.project.eventcalendar.protobuf;

public interface UserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdj.project.eventcalendar.protobuf.UserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
